version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-youtube-livetrim"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a44pg41y2qcm"
s3_prefix = "lambda-youtube-livetrim"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
