version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "youtube-download-serverless-be"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-26b0jbb1cg8w"
s3_prefix = "youtube-download-serverless-be"
region = "ap-northeast-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "TrimmedResultBucketName=\"trim-result-bucket\" TrimCacheDynTableName=\"trim-result-lookup-table\" TrimCacheDynTablePartitionKey=\"VideoId\" TrimCacheDynTableSortKey=\"Track\""
image_repositories = []
