AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for youtube downloader serverless backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  TrimmedResultBucketName:
    Type: String
    Default: livetrim-result-bucket

Resources:
  GetYoutubeVideoInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/search/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SearchYoutubeVideoRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: get
      Layers:
        - !Ref SearchLayer

  LiveTrimYoutubeVideoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/livetrim/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LiveTrimRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /livetrim
            Method: post
      Layers:
        - !Ref LiveTrimLayer
        - !Sub "arn:aws:lambda:us-east-1:392039937679:layer:FFmpegLayer:2"
        
      
      Environment:
        Variables:
          TrimmedResultBucket: !Ref TrimmedResultBucketName

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TrimmedResultBucketName

  SearchLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/search-layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  LiveTrimLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/livetrim-layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  FFmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri:
        Bucket: aws-sam-cli-managed-default-samclisourcebucket-a44pg41y2qcm
        Key: ffmpeg.zip
      RetentionPolicy: Retain
      LicenseInfo: GPL-2.0-or-later

  TrimResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TrimmedResultBucketName

Outputs:
  LiveTrimYoutubeVideoFunction:
    Description: "Youtube Live Trim Function"
    Value: !GetAtt LiveTrimYoutubeVideoFunction.Arn
  
  GetYoutubeVideoInfoFunction:
    Description: "Get Youtube Video Information Function"
    Value: !GetAtt GetYoutubeVideoInfoFunction.Arn

